export default [
  {
    name:'home',
    path:'/home',
    component:()=>import('@/pages/Home'),
    meta:{showFooter:true},
  },
  {
    name:'search',
    path:'/search',
    component:()=>import('@/pages/Search'),
    meta:{showFooter:true},
  },
  {
    name:'order',
    path:'/order',
    component:()=>import('@/pages/Order'),
    meta:{showFooter:true},
  },
  {
    name:'me',
    path:'/me',
    component:()=>import('@/pages/Me'),
    meta:{showFooter:true},
  },
  {
    name:'login',
    path:'/login',
    component:()=>import('@/pages/Login'),
    meta:{showFooter:false},
  },
  {
    name:'shop',
    path:'/shop',
    component:()=>import('@/pages/Shop'),
    meta:{showFooter:false},
    children:[
      {
        path:'/shop/goods',
        component:()=>import('@/pages/Shop/ShopGoods'),
        meta:{showFooter:false},
      },
      {
        path:'/shop/info',
        component:()=>import('@/pages/Shop/ShopInfo'),
        meta:{showFooter:false},
      },
      {
        path:'/shop/ratings',
        component:()=>import('@/pages/Shop/ShopRatings'),
        meta:{showFooter:false},
      },
      //重定向
      {
        path:'/shop',
        redirect:'/shop/goods',
      },
    ],
  },

  //重定向
  {
    path:'/',
    redirect:'/home',
  },
]
